# Generated by Django 5.0.4 on 2024-04-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PleaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Price', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
