# Generated by Django 5.0.4 on 2024-04-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleace', '0002_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
    ]
