# Generated by Django 5.0.4 on 2024-04-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleace', '0003_remove_employee_cv_remove_employee_department_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='department_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pleace.department_id'),
            preserve_default=False,
        ),
    ]
