# Generated by Django 5.0.2 on 2024-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleace', '0006_rename_location_pleaceinformation_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts_support', models.CharField(max_length=100)),
                ('Rooms', models.CharField(max_length=100)),
                ('Toilets', models.CharField(max_length=100)),
            ],
        ),
    ]
