# Generated by Django 5.0.4 on 2024-07-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='placeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(upload_to='', verbose_name='images/front')),
                ('back', models.ImageField(upload_to='', verbose_name='images/back')),
                ('right', models.ImageField(upload_to='', verbose_name='images/right')),
                ('left', models.ImageField(upload_to='', verbose_name='images/left')),
            ],
        ),
        migrations.CreateModel(
            name='PleaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=300)),
                ('street_adress', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True)),
                ('facebook', models.URLField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True, max_length=300)),
                ('images', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
