# Generated by Django 5.0.4 on 2024-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleaceinformation',
            name='images',
        ),
    ]
