# Generated by Django 5.0.4 on 2024-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_pleaceinformation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimages',
            name='back',
            field=models.ImageField(upload_to='images/back'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='front',
            field=models.ImageField(upload_to='images/front'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='left',
            field=models.ImageField(upload_to='images/left'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='right',
            field=models.ImageField(upload_to='images/right'),
        ),
    ]
