# Generated by Django 5.0.4 on 2024-07-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_placeimages_back_alter_placeimages_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimages',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.pleaceinformation'),
            preserve_default=False,
        ),
    ]
