# Generated by Django 5.0.4 on 2024-07-30 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_placeimages_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pleaceinformation',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='images/profiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='back',
            field=models.ImageField(default='default_image.png', upload_to='images/back'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='front',
            field=models.ImageField(default='default_image.png', upload_to='images/front'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='left',
            field=models.ImageField(default='default_image.png', upload_to='images/left'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='right',
            field=models.ImageField(default='default_image.png', upload_to='images/right'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ManyToManyField(to='place.pleaceinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
